### ISSUE TITLE
port recent changes from bleve

### ISSUE THREAD

**Issue by mschoch** [blugelabs/bluge#45]
Especially this security bug fix for HTML highlighting: https://github.com/blevesearch/bleve/commit/b9b775998330bf9efdc8748021a80e38fc1e250c

**Comment by mschoch** [comment]
- [x] d6a3fe28 (HEAD -> master, tag: v1.0.14, origin/master, origin/HEAD) prepare for blevex go.mod (#1519)
- [x] c3457bb7 (tag: v1.0.13) prepare to support zap v15.0.2 (#1499)
- [x] 4b6bddf7 fix analyzer lookup when field name contains dot (#1496)
- [ ] e24b3afc Remove default from text description (#1489)
- [x] c67bc71f Fix DocValuesDynamic's json-ability within IndexMappingImpl (#1485)
- [x] 7e8fd30c (tag: v1.0.12) prepare bleve v1.0.12 (#1483)
- [x] 7efdbbb6 (tag: v1.0.11) add support for zap v15 and update zap version (#1482)
- [ ] b9b77599 escape the input text in HTML highlighter when adding <mark> tags, fixes #1464 (#1465)
- [ ] cc29456f Fixed ASCII folding of \u24A2 (#1434)
- [x] 3bb3c7b4 Shutdown analysis queue (#1414)
- [ ] bffe7ea0 add go 1.15.x to the testing matrix (#1468)
- [x] 7a377b75 Index is always left closed when opening process failed (#1479)
- [x] 0197e8dd an optimization fix test was no longer helping (#1459)
- [ ] 99e9e901 New stats for reclaimable disk space from scorch index (#1470)
- [ ] c997b4a5 fix tests on go 1.15 (#1466)

**Comment by mschoch** [comment]
While reviewing bleve SHA b9b77599 for porting to bluge, I discovered that a part of that fix had been omitted by mistake.

The details of that mistake are here: https://github.com/blevesearch/bleve/issues/1529

The proposed fix (under review) for that mistake is here: https://github.com/blevesearch/bleve/pull/1530

**Comment by mschoch** [comment]
I'm opting to not port the reclaimable disk space stat at this time (ref `99e9e901`)
